"""empty message

Revision ID: 2d1b9e1512d0
Revises: 3f6c051c69a3
Create Date: 2015-10-21 15:02:22.022045

"""

# revision identifiers, used by Alembic.
revision = '2d1b9e1512d0'
down_revision = '3f6c051c69a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
