"""Add non-nullable year field to automobiles

Revision ID: 395cec770df2
Revises: f7c7d7bf5a1
Create Date: 2015-10-22 00:43:30.076142

"""

# revision identifiers, used by Alembic.
revision = '395cec770df2'
down_revision = 'f7c7d7bf5a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automobiles', sa.Column('year', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('automobiles', 'year')
    ### end Alembic commands ###
