"""Re-add automobiles table, with required foreign key

Revision ID: 3f6c051c69a3
Revises: 6c2faa7cde6
Create Date: 2015-10-21 14:31:28.071348

"""

# revision identifiers, used by Alembic.
revision = '3f6c051c69a3'
down_revision = '6c2faa7cde6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automobiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('automobiles')
    ### end Alembic commands ###
