"""Drop automobiles table

Revision ID: 6c2faa7cde6
Revises: 13b1250e6074
Create Date: 2015-10-21 14:30:23.162676

"""

# revision identifiers, used by Alembic.
revision = '6c2faa7cde6'
down_revision = '13b1250e6074'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('automobiles')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automobiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('manufacturer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], [u'manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
